version: '3.8'

services:
  appcpf:
    container_name: appcpf
    image: convergencia/cpf
    build: 
      context: projeto-cpf
      dockerfile: Dockerfile
    #restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - tmp:/tmp
    networks:
      - app-network
  applogin:
    depends_on:
      - appcpf
    container_name: applogin
    build: 
      context: projeto-login
      dockerfile: Dockerfile
    image: convergencia/login
    #restart: unless-stopped
    ports:
      - 8090:8090
    stdin_open: true
    tty: true
    volumes:
      - tmp2:/tmp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  tmp:
  tmp2:
